# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bb9a3443290b9ec865434713b60dc70"
name = "revenue-optimiser"
handle = "revenue-optimiser"
application_url = "https://red-comfortable-years-ranges.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://red-comfortable-years-ranges.trycloudflare.com/auth/callback", "https://red-comfortable-years-ranges.trycloudflare.com/auth/shopify/callback", "https://red-comfortable-years-ranges.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
